[package]
name = "name_serde"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
holda = { version = "0.1.0", path = "../..", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
